name: production

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish with semanti-release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github @semantic-release/git

      - name: Publish new release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Resolve dependencies
      #   run: npm install
